# Generated by Django 2.2.6 on 2019-12-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20191212_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='user_answers',
            field=models.TextField(blank=True, default='', verbose_name='User Answers'),
        ),
    ]
