# Generated by Django 2.2.6 on 2019-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20191215_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rule1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rule2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rule3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rule4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rule5',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
